/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs102941TrustLists"
 * 	found in "../../asn1/../ttcn/AtsPki/lib/asn1/EtsiTs102941TrustLists.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "EtsiTs103097Certificate.h"
#include "Url.h"
#include <constr_SEQUENCE.h>
#ifndef	_AaEntry_H_
#define	_AaEntry_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AaEntry */
typedef struct AaEntry {
	EtsiTs103097Certificate_t	 aaCertificate;
	Url_t	 accessPoint;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AaEntry_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AaEntry;
extern asn_SEQUENCE_specifics_t asn_SPC_AaEntry_specs_1;
extern asn_TYPE_member_t asn_MBR_AaEntry_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _AaEntry_H_ */
#include <asn_internal.h>
