/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1Acpc"
 * 	found in "../../asn1/../ttcn/AtsPki/lib/asn1/ieee_1609.2.1/Ieee1609Dot2Dot1Acpc.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "AprvBinaryTree.h"
#include "IndividualAprv.h"
#include <constr_CHOICE.h>
#ifndef	_AcpcPdu_H_
#define	_AcpcPdu_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AcpcPdu_PR {
	AcpcPdu_PR_NOTHING,	/* No components present */
	AcpcPdu_PR_tree,
	AcpcPdu_PR_aprv
	/* Extensions may appear below */
	
} AcpcPdu_PR;

/* AcpcPdu */
typedef struct AcpcPdu {
	AcpcPdu_PR present;
	union AcpcPdu_u {
		AprvBinaryTree_t	 tree;
		IndividualAprv_t	 aprv;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AcpcPdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AcpcPdu;

#ifdef __cplusplus
}
#endif

#endif	/* _AcpcPdu_H_ */
#include <asn_internal.h>
