/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Iso21177AdaptorLayer"
 * 	found in "../../asn1/../ttcn/Ats21177/21177/EN_ISO_21177_adaptor_layer.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include <OCTET_STRING.h>
#ifndef	_Apdu_H_
#define	_Apdu_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Apdu */
typedef OCTET_STRING_t	 Apdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Apdu;
asn_struct_free_f Apdu_free;
asn_struct_print_f Apdu_print;
asn_constr_check_f Apdu_constraint;
ber_type_decoder_f Apdu_decode_ber;
der_type_encoder_f Apdu_encode_der;
xer_type_decoder_f Apdu_decode_xer;
xer_type_encoder_f Apdu_encode_xer;
jer_type_encoder_f Apdu_encode_jer;
oer_type_decoder_f Apdu_decode_oer;
oer_type_encoder_f Apdu_encode_oer;
per_type_decoder_f Apdu_decode_uper;
per_type_encoder_f Apdu_encode_uper;
per_type_decoder_f Apdu_decode_aper;
per_type_encoder_f Apdu_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Apdu_H_ */
#include <asn_internal.h>
