/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Iso21177AccessControl"
 * 	found in "../../asn1/../ttcn/Ats21177/21177/EN_ISO_21177_access_control.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#include "PsidSspRange.h"
#include <IA5String.h>
#include <OCTET_STRING.h>
#include <constr_CHOICE.h>
#ifndef	_AtomicExtendedAuthRequest_H_
#define	_AtomicExtendedAuthRequest_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AtomicExtendedAuthRequest_PR {
	AtomicExtendedAuthRequest_PR_NOTHING,	/* No components present */
	AtomicExtendedAuthRequest_PR_psid,
	AtomicExtendedAuthRequest_PR_psidSspRange,
	AtomicExtendedAuthRequest_PR_idRegExp,
	AtomicExtendedAuthRequest_PR_issuer
	/* Extensions may appear below */
	
} AtomicExtendedAuthRequest_PR;

/* AtomicExtendedAuthRequest */
typedef struct AtomicExtendedAuthRequest {
	AtomicExtendedAuthRequest_PR present;
	union AtomicExtendedAuthRequest_u {
		long	 psid;
		PsidSspRange_t	 psidSspRange;
		IA5String_t	 idRegExp;
		OCTET_STRING_t	 issuer;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AtomicExtendedAuthRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AtomicExtendedAuthRequest;
extern asn_CHOICE_specifics_t asn_SPC_AtomicExtendedAuthRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_AtomicExtendedAuthRequest_1[4];
extern asn_per_constraints_t asn_PER_type_AtomicExtendedAuthRequest_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _AtomicExtendedAuthRequest_H_ */
#include <asn_internal.h>
