/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcGeneric"
 * 	found in "../../asn1/../ttcn/AtsIS/lib/asn1/iso-patched/EfcDsrcGeneric.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#ifndef	_AttributeIdList_H_
#define	_AttributeIdList_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AttributeIdList */
typedef struct AttributeIdList {
	A_SEQUENCE_OF(long) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AttributeIdList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AttributeIdList;
extern asn_SET_OF_specifics_t asn_SPC_AttributeIdList_specs_1;
extern asn_TYPE_member_t asn_MBR_AttributeIdList_1[1];
extern asn_per_constraints_t asn_PER_type_AttributeIdList_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _AttributeIdList_H_ */
#include <asn_internal.h>
