/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "AVIAEINumberingAndDataStructures"
 * 	found in "../../asn1/../ttcn/../build/asn1/ISO_TS_14816/AVIAEINumberingAndDataStructures.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_AVIAEIIssuerIdentifier_H_
#define	_AVIAEIIssuerIdentifier_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AVIAEIIssuerIdentifier */
typedef long	 AVIAEIIssuerIdentifier_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AVIAEIIssuerIdentifier_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AVIAEIIssuerIdentifier;
asn_struct_free_f AVIAEIIssuerIdentifier_free;
asn_struct_print_f AVIAEIIssuerIdentifier_print;
asn_constr_check_f AVIAEIIssuerIdentifier_constraint;
ber_type_decoder_f AVIAEIIssuerIdentifier_decode_ber;
der_type_encoder_f AVIAEIIssuerIdentifier_encode_der;
xer_type_decoder_f AVIAEIIssuerIdentifier_decode_xer;
xer_type_encoder_f AVIAEIIssuerIdentifier_encode_xer;
jer_type_encoder_f AVIAEIIssuerIdentifier_encode_jer;
oer_type_decoder_f AVIAEIIssuerIdentifier_decode_oer;
oer_type_encoder_f AVIAEIIssuerIdentifier_encode_oer;
per_type_decoder_f AVIAEIIssuerIdentifier_decode_uper;
per_type_encoder_f AVIAEIIssuerIdentifier_encode_uper;
per_type_decoder_f AVIAEIIssuerIdentifier_decode_aper;
per_type_encoder_f AVIAEIIssuerIdentifier_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _AVIAEIIssuerIdentifier_H_ */
#include <asn_internal.h>
