/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "../../asn1/../ttcn/AtsIS/lib/asn1/iso-patched/EfcDsrcApplication.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "Int2.h"
#include <constr_SEQUENCE.h>
#ifndef	_AxleWeightLimits_H_
#define	_AxleWeightLimits_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AxleWeightLimits */
typedef struct AxleWeightLimits {
	Int2_t	 maxLadenweightOnAxle1;
	Int2_t	 maxLadenweightOnAxle2;
	Int2_t	 maxLadenweightOnAxle3;
	Int2_t	 maxLadenweightOnAxle4;
	Int2_t	 maxLadenweightOnAxle5;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AxleWeightLimits_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AxleWeightLimits;
extern asn_SEQUENCE_specifics_t asn_SPC_AxleWeightLimits_specs_1;
extern asn_TYPE_member_t asn_MBR_AxleWeightLimits_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _AxleWeightLimits_H_ */
#include <asn_internal.h>
