/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1CamRaInterface"
 * 	found in "../../asn1/../ttcn/AtsPki/lib/asn1/ieee_1609.2.1/Ieee1609Dot2Dot1CamRaInterface.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "EccP256CurvePoint.h"
#ifndef	_BlindedKey_H_
#define	_BlindedKey_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BlindedKey */
typedef EccP256CurvePoint_t	 BlindedKey_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_BlindedKey_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_BlindedKey;
asn_struct_free_f BlindedKey_free;
asn_struct_print_f BlindedKey_print;
asn_constr_check_f BlindedKey_constraint;
ber_type_decoder_f BlindedKey_decode_ber;
der_type_encoder_f BlindedKey_encode_der;
xer_type_decoder_f BlindedKey_decode_xer;
xer_type_encoder_f BlindedKey_encode_xer;
jer_type_encoder_f BlindedKey_encode_jer;
oer_type_decoder_f BlindedKey_decode_oer;
oer_type_encoder_f BlindedKey_encode_oer;
per_type_decoder_f BlindedKey_decode_uper;
per_type_encoder_f BlindedKey_encode_uper;
per_type_decoder_f BlindedKey_decode_aper;
per_type_encoder_f BlindedKey_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _BlindedKey_H_ */
#include <asn_internal.h>
