/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Iso21177AccessControl"
 * 	found in "../../asn1/../ttcn/Ats21177/21177/EN_ISO_21177_access_control.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "HashedId8.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>
#ifndef	_CertChainRequest_H_
#define	_CertChainRequest_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CertChainRequest */
typedef struct CertChainRequest {
	HashedId8_t	 issuerId;
	long	 length;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CertChainRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertChainRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_CertChainRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_CertChainRequest_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _CertChainRequest_H_ */
#include <asn_internal.h>
