/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "GDD"
 * 	found in "../../asn1/../ttcn/AtsIS/lib/asn1/iso-patched/GDD.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_Code_Units_H_
#define	_Code_Units_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Code_Units {
	Code_Units_kmperh	= 0,
	Code_Units_milesperh	= 1,
	Code_Units_kilometre	= 2,
	Code_Units_metre	= 3,
	Code_Units_decimetre	= 4,
	Code_Units_centimetre	= 5,
	Code_Units_mile	= 6,
	Code_Units_yard	= 7,
	Code_Units_foot	= 8,
	Code_Units_minutesOfTime	= 9,
	Code_Units_tonnes	= 10,
	Code_Units_hundredkg	= 11,
	Code_Units_pound	= 12,
	Code_Units_rateOfIncline	= 13,
	Code_Units_durationinminutes	= 14
} e_Code_Units;

/* Code-Units */
typedef long	 Code_Units_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Code_Units_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Code_Units;
asn_struct_free_f Code_Units_free;
asn_struct_print_f Code_Units_print;
asn_constr_check_f Code_Units_constraint;
ber_type_decoder_f Code_Units_decode_ber;
der_type_encoder_f Code_Units_encode_der;
xer_type_decoder_f Code_Units_decode_xer;
xer_type_encoder_f Code_Units_encode_xer;
jer_type_encoder_f Code_Units_encode_jer;
oer_type_decoder_f Code_Units_decode_oer;
oer_type_encoder_f Code_Units_encode_oer;
per_type_decoder_f Code_Units_decode_uper;
per_type_encoder_f Code_Units_encode_uper;
per_type_decoder_f Code_Units_decode_aper;
per_type_encoder_f Code_Units_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Code_Units_H_ */
#include <asn_internal.h>
