/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpC-noCircular"
 * 	found in "../../asn1/../ttcn/AtsIS/lib/asn1/iso-patched/AddGrpC_noCircular.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "PtvRequestType.h"
#include <constr_SEQUENCE.h>
#ifndef	_Control_addGrpC_H_
#define	_Control_addGrpC_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Control-addGrpC */
typedef struct Control_addGrpC {
	PtvRequestType_t	 ptvRequest;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Control_addGrpC_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Control_addGrpC;

#ifdef __cplusplus
}
#endif

#endif	/* _Control_addGrpC_H_ */
#include <asn_internal.h>
