/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "../../asn1/../ttcn/AtsIS/lib/asn1/iso-patched/EfcDsrcApplication.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include <NativeEnumerated.h>
#ifndef	_CopValue_H_
#define	_CopValue_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CopValue {
	CopValue_noEntry	= 0,
	CopValue_co2class1	= 1,
	CopValue_co2class2	= 2,
	CopValue_co2class3	= 3,
	CopValue_co2class4	= 4,
	CopValue_co2class5	= 5,
	CopValue_co2class6	= 6,
	CopValue_co2class7	= 7,
	CopValue_reservedforUse	= 8
} e_CopValue;

/* CopValue */
typedef long	 CopValue_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_CopValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_CopValue;
extern const asn_INTEGER_specifics_t asn_SPC_CopValue_specs_1;
asn_struct_free_f CopValue_free;
asn_struct_print_f CopValue_print;
asn_constr_check_f CopValue_constraint;
ber_type_decoder_f CopValue_decode_ber;
der_type_encoder_f CopValue_encode_der;
xer_type_decoder_f CopValue_decode_xer;
xer_type_encoder_f CopValue_encode_xer;
jer_type_encoder_f CopValue_encode_jer;
oer_type_decoder_f CopValue_decode_oer;
oer_type_encoder_f CopValue_encode_oer;
per_type_decoder_f CopValue_decode_uper;
per_type_encoder_f CopValue_encode_uper;
per_type_decoder_f CopValue_decode_aper;
per_type_encoder_f CopValue_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _CopValue_H_ */
#include <asn_internal.h>
