/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2BaseTypes"
 * 	found in "../../asn1/../ttcn/AtsSecurity/lib/asn1/ieee1609dot2/Ieee1609Dot2BaseTypes.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "CountryOnly.h"
#include "SequenceOfRegionAndSubregions.h"
#include <constr_SEQUENCE.h>
#ifndef	_CountryAndSubregions_H_
#define	_CountryAndSubregions_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CountryAndSubregions */
typedef struct CountryAndSubregions {
	CountryOnly_t	 country;
	SequenceOfRegionAndSubregions_t	 regionAndSubregions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CountryAndSubregions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CountryAndSubregions;
extern asn_SEQUENCE_specifics_t asn_SPC_CountryAndSubregions_specs_1;
extern asn_TYPE_member_t asn_MBR_CountryAndSubregions_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _CountryAndSubregions_H_ */
#include <asn_internal.h>
