/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "../../asn1/../ttcn/AtsIS/lib/asn1/iso-patched/EfcDsrcApplication.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "DateCompact.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>
#ifndef	_DateAndTime_H_
#define	_DateAndTime_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DateAndTime */
typedef struct DateAndTime {
	DateCompact_t	 timeDate;
	struct DateAndTime__timeCompact {
		long	 hours;
		long	 mins;
		long	 double_secs;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} timeCompact;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DateAndTime_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DateAndTime;
extern asn_SEQUENCE_specifics_t asn_SPC_DateAndTime_specs_1;
extern asn_TYPE_member_t asn_MBR_DateAndTime_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _DateAndTime_H_ */
#include <asn_internal.h>
