/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs102941TrustLists"
 * 	found in "../../asn1/../ttcn/AtsPki/lib/asn1/EtsiTs102941TrustLists.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "CtlFormat.h"
#ifndef	_DeltaCtl_H_
#define	_DeltaCtl_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DeltaCtl */
typedef CtlFormat_t	 DeltaCtl_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DeltaCtl;
asn_struct_free_f DeltaCtl_free;
asn_struct_print_f DeltaCtl_print;
asn_constr_check_f DeltaCtl_constraint;
ber_type_decoder_f DeltaCtl_decode_ber;
der_type_encoder_f DeltaCtl_encode_der;
xer_type_decoder_f DeltaCtl_decode_xer;
xer_type_encoder_f DeltaCtl_encode_xer;
jer_type_encoder_f DeltaCtl_encode_jer;
oer_type_decoder_f DeltaCtl_decode_oer;
oer_type_encoder_f DeltaCtl_encode_oer;
per_type_decoder_f DeltaCtl_decode_uper;
per_type_encoder_f DeltaCtl_encode_uper;
per_type_decoder_f DeltaCtl_decode_aper;
per_type_encoder_f DeltaCtl_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _DeltaCtl_H_ */
#include <asn_internal.h>
