/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1EcaEeInterface"
 * 	found in "../../asn1/../ttcn/AtsPki/lib/asn1/ieee_1609.2.1/Ieee1609Dot2Dot1EcaEeInterface.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "Uint8.h"
#include "HashedId8.h"
#include "SequenceOfCertificate.h"
#include "Certificate.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>
#ifndef	_EcaEeCertResponse_H_
#define	_EcaEeCertResponse_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EcaEeCertResponse */
typedef struct EcaEeCertResponse {
	Uint8_t	 version;
	HashedId8_t	 requestHash;
	SequenceOfCertificate_t	 ecaCertChain;
	Certificate_t	 certificate;
	OCTET_STRING_t	*privateKeyInfo;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EcaEeCertResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EcaEeCertResponse;
extern asn_SEQUENCE_specifics_t asn_SPC_EcaEeCertResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_EcaEeCertResponse_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _EcaEeCertResponse_H_ */
#include <asn_internal.h>
