/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1AcaRaInterface"
 * 	found in "../../asn1/../ttcn/AtsPki/lib/asn1/ieee_1609.2.1/Ieee1609Dot2Dot1AcaRaInterface.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "Uint8.h"
#include "LaId.h"
#include "Ieee1609Dot2Data-SymmEncryptedSingleRecipient.h"
#include <constr_SEQUENCE.h>
#ifndef	_EncryptedIndividualPLV_H_
#define	_EncryptedIndividualPLV_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EncryptedIndividualPLV */
typedef struct EncryptedIndividualPLV {
	Uint8_t	 version;
	LaId_t	 laId;
	Ieee1609Dot2Data_SymmEncryptedSingleRecipient_438P0_t	 encPlv;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EncryptedIndividualPLV_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EncryptedIndividualPLV;
extern asn_SEQUENCE_specifics_t asn_SPC_EncryptedIndividualPLV_specs_1;
extern asn_TYPE_member_t asn_MBR_EncryptedIndividualPLV_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _EncryptedIndividualPLV_H_ */
#include <asn_internal.h>
