/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Iso21177AccessControl"
 * 	found in "../../asn1/../ttcn/Ats21177/21177/EN_ISO_21177_access_control.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "EnhancedAuthPduId.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "SpakeRequest.h"
#include "SpakeResponse.h"
#include "SpakeRequesterResponse.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>
#ifndef	_EnhancedAuthPdu_H_
#define	_EnhancedAuthPdu_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EnhancedAuthPdu__value_PR {
	EnhancedAuthPdu__value_PR_NOTHING,	/* No components present */
	EnhancedAuthPdu__value_PR_SpakeRequest,
	EnhancedAuthPdu__value_PR_SpakeResponse,
	EnhancedAuthPdu__value_PR_SpakeRequesterResponse
} EnhancedAuthPdu__value_PR;

/* EnhancedAuthPdu */
typedef struct EnhancedAuthPdu {
	EnhancedAuthPduId_t	 messageId;
	struct EnhancedAuthPdu__value {
		EnhancedAuthPdu__value_PR present;
		union EnhancedAuthPdu__value_u {
			SpakeRequest_t	 SpakeRequest;
			SpakeResponse_t	 SpakeResponse;
			SpakeRequesterResponse_t	 SpakeRequesterResponse;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EnhancedAuthPdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EnhancedAuthPdu;
extern asn_SEQUENCE_specifics_t asn_SPC_EnhancedAuthPdu_specs_1;
extern asn_TYPE_member_t asn_MBR_EnhancedAuthPdu_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _EnhancedAuthPdu_H_ */
#include <asn_internal.h>
