/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Iso21177AccessControl"
 * 	found in "../../asn1/../ttcn/Ats21177/21177/EN_ISO_21177_access_control.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_EnhancedAuthPduId_H_
#define	_EnhancedAuthPduId_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EnhancedAuthPduId */
typedef long	 EnhancedAuthPduId_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_EnhancedAuthPduId_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_EnhancedAuthPduId;
asn_struct_free_f EnhancedAuthPduId_free;
asn_struct_print_f EnhancedAuthPduId_print;
asn_constr_check_f EnhancedAuthPduId_constraint;
ber_type_decoder_f EnhancedAuthPduId_decode_ber;
der_type_encoder_f EnhancedAuthPduId_encode_der;
xer_type_decoder_f EnhancedAuthPduId_decode_xer;
xer_type_encoder_f EnhancedAuthPduId_encode_xer;
jer_type_encoder_f EnhancedAuthPduId_encode_jer;
oer_type_decoder_f EnhancedAuthPduId_decode_oer;
oer_type_encoder_f EnhancedAuthPduId_encode_oer;
per_type_decoder_f EnhancedAuthPduId_decode_uper;
per_type_encoder_f EnhancedAuthPduId_encode_uper;
per_type_decoder_f EnhancedAuthPduId_decode_aper;
per_type_encoder_f EnhancedAuthPduId_encode_aper;
#define EnhancedAuthPduId_enhancedAuthPduId_reserved	((EnhancedAuthPduId_t)0)
#define EnhancedAuthPduId_spakeRequestId	((EnhancedAuthPduId_t)1)
#define EnhancedAuthPduId_spakeResponseId	((EnhancedAuthPduId_t)2)
#define EnhancedAuthPduId_spakeRequesterResponseId	((EnhancedAuthPduId_t)3)

#ifdef __cplusplus
}
#endif

#endif	/* _EnhancedAuthPduId_H_ */
#include <asn_internal.h>
