/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs102941MessagesCa"
 * 	found in "../../asn1/../ttcn/AtsPki/lib/asn1/EtsiTs102941MessagesCa.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "Version.h"
#include "EtsiTs102941DataContent.h"
#include <constr_SEQUENCE.h>
#ifndef	_EtsiTs102941Data_H_
#define	_EtsiTs102941Data_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EtsiTs102941Data */
typedef struct EtsiTs102941Data {
	Version_t	 version;
	EtsiTs102941DataContent_t	 content;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EtsiTs102941Data_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EtsiTs102941Data;

#ifdef __cplusplus
}
#endif

#endif	/* _EtsiTs102941Data_H_ */
#include <asn_internal.h>
