/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Iso21177AccessControl"
 * 	found in "../../asn1/../ttcn/Ats21177/21177/EN_ISO_21177_access_control.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "ExtendedAuthPduId.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "ExtendedAuthRequest.h"
#include "ExtendedAuthResponse.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>
#ifndef	_ExtendedAuthPdu_H_
#define	_ExtendedAuthPdu_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ExtendedAuthPdu__value_PR {
	ExtendedAuthPdu__value_PR_NOTHING,	/* No components present */
	ExtendedAuthPdu__value_PR_ExtendedAuthRequest,
	ExtendedAuthPdu__value_PR_ExtendedAuthResponse
} ExtendedAuthPdu__value_PR;

/* ExtendedAuthPdu */
typedef struct ExtendedAuthPdu {
	ExtendedAuthPduId_t	 messageId;
	struct ExtendedAuthPdu__value {
		ExtendedAuthPdu__value_PR present;
		union ExtendedAuthPdu__value_u {
			ExtendedAuthRequest_t	 ExtendedAuthRequest;
			ExtendedAuthResponse_t	 ExtendedAuthResponse;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ExtendedAuthPdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExtendedAuthPdu;
extern asn_SEQUENCE_specifics_t asn_SPC_ExtendedAuthPdu_specs_1;
extern asn_TYPE_member_t asn_MBR_ExtendedAuthPdu_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ExtendedAuthPdu_H_ */
#include <asn_internal.h>
