/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "../../asn1/../ttcn/../build/asn1/ISO_TS_19321/IVI.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_FrictionCoefficient_H_
#define	_FrictionCoefficient_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FrictionCoefficient */
typedef long	 FrictionCoefficient_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FrictionCoefficient_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FrictionCoefficient;
asn_struct_free_f FrictionCoefficient_free;
asn_struct_print_f FrictionCoefficient_print;
asn_constr_check_f FrictionCoefficient_constraint;
ber_type_decoder_f FrictionCoefficient_decode_ber;
der_type_encoder_f FrictionCoefficient_encode_der;
xer_type_decoder_f FrictionCoefficient_decode_xer;
xer_type_encoder_f FrictionCoefficient_encode_xer;
jer_type_encoder_f FrictionCoefficient_encode_jer;
oer_type_decoder_f FrictionCoefficient_decode_oer;
oer_type_encoder_f FrictionCoefficient_encode_oer;
per_type_decoder_f FrictionCoefficient_decode_uper;
per_type_encoder_f FrictionCoefficient_encode_uper;
per_type_decoder_f FrictionCoefficient_decode_aper;
per_type_encoder_f FrictionCoefficient_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FrictionCoefficient_H_ */
#include <asn_internal.h>
