/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "../../asn1/../ttcn/AtsIS/lib/asn1/iso-patched/EfcDsrcApplication.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_FutureCharacteristics_H_
#define	_FutureCharacteristics_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FutureCharacteristics {
	FutureCharacteristics_noEntry	= 0,
	FutureCharacteristics_airSuspension	= 1
} e_FutureCharacteristics;

/* FutureCharacteristics */
typedef long	 FutureCharacteristics_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FutureCharacteristics_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FutureCharacteristics;
asn_struct_free_f FutureCharacteristics_free;
asn_struct_print_f FutureCharacteristics_print;
asn_constr_check_f FutureCharacteristics_constraint;
ber_type_decoder_f FutureCharacteristics_decode_ber;
der_type_encoder_f FutureCharacteristics_encode_der;
xer_type_decoder_f FutureCharacteristics_decode_xer;
xer_type_encoder_f FutureCharacteristics_encode_xer;
jer_type_encoder_f FutureCharacteristics_encode_jer;
oer_type_decoder_f FutureCharacteristics_decode_oer;
oer_type_encoder_f FutureCharacteristics_encode_oer;
per_type_decoder_f FutureCharacteristics_decode_uper;
per_type_encoder_f FutureCharacteristics_encode_uper;
per_type_decoder_f FutureCharacteristics_decode_aper;
per_type_encoder_f FutureCharacteristics_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FutureCharacteristics_H_ */
#include <asn_internal.h>
