/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2"
 * 	found in "../../asn1/../ttcn/AtsSecurity/lib/asn1/ieee1609dot2/Ieee1609Dot2.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_HeaderInfoContributorId_H_
#define	_HeaderInfoContributorId_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HeaderInfoContributorId */
typedef long	 HeaderInfoContributorId_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_HeaderInfoContributorId_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_HeaderInfoContributorId;
asn_struct_free_f HeaderInfoContributorId_free;
asn_struct_print_f HeaderInfoContributorId_print;
asn_constr_check_f HeaderInfoContributorId_constraint;
ber_type_decoder_f HeaderInfoContributorId_decode_ber;
der_type_encoder_f HeaderInfoContributorId_encode_der;
xer_type_decoder_f HeaderInfoContributorId_decode_xer;
xer_type_encoder_f HeaderInfoContributorId_encode_xer;
jer_type_encoder_f HeaderInfoContributorId_encode_jer;
oer_type_decoder_f HeaderInfoContributorId_decode_oer;
oer_type_encoder_f HeaderInfoContributorId_encode_oer;
per_type_decoder_f HeaderInfoContributorId_decode_uper;
per_type_encoder_f HeaderInfoContributorId_encode_uper;
per_type_decoder_f HeaderInfoContributorId_decode_aper;
per_type_encoder_f HeaderInfoContributorId_encode_aper;
#define HeaderInfoContributorId_etsiHeaderInfoContributorId	((HeaderInfoContributorId_t)2)

#ifdef __cplusplus
}
#endif

#endif	/* _HeaderInfoContributorId_H_ */
#include <asn_internal.h>
