/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1CertManagement"
 * 	found in "../../asn1/../ttcn/AtsPki/lib/asn1/ieee_1609.2.1/Ieee1609Dot2Dot1CertManagement.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_Ieee1609dot2dot1MsctlType_H_
#define	_Ieee1609dot2dot1MsctlType_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Ieee1609dot2dot1MsctlType */
typedef long	 Ieee1609dot2dot1MsctlType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ieee1609dot2dot1MsctlType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ieee1609dot2dot1MsctlType;
asn_struct_free_f Ieee1609dot2dot1MsctlType_free;
asn_struct_print_f Ieee1609dot2dot1MsctlType_print;
asn_constr_check_f Ieee1609dot2dot1MsctlType_constraint;
ber_type_decoder_f Ieee1609dot2dot1MsctlType_decode_ber;
der_type_encoder_f Ieee1609dot2dot1MsctlType_encode_der;
xer_type_decoder_f Ieee1609dot2dot1MsctlType_decode_xer;
xer_type_encoder_f Ieee1609dot2dot1MsctlType_encode_xer;
jer_type_encoder_f Ieee1609dot2dot1MsctlType_encode_jer;
oer_type_decoder_f Ieee1609dot2dot1MsctlType_decode_oer;
oer_type_encoder_f Ieee1609dot2dot1MsctlType_encode_oer;
per_type_decoder_f Ieee1609dot2dot1MsctlType_decode_uper;
per_type_encoder_f Ieee1609dot2dot1MsctlType_encode_uper;
per_type_decoder_f Ieee1609dot2dot1MsctlType_decode_aper;
per_type_encoder_f Ieee1609dot2dot1MsctlType_encode_aper;
#define Ieee1609dot2dot1MsctlType_fullIeeeCtl	((Ieee1609dot2dot1MsctlType_t)1)

#ifdef __cplusplus
}
#endif

#endif	/* _Ieee1609dot2dot1MsctlType_H_ */
#include <asn_internal.h>
