/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Iso21177AccessControl"
 * 	found in "../../asn1/../ttcn/Ats21177/21177/EN_ISO_21177_access_control.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "AtomicExtendedAuthRequest.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_CHOICE.h>
#ifndef	_InnerExtendedAuthRequest_H_
#define	_InnerExtendedAuthRequest_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum InnerExtendedAuthRequest_PR {
	InnerExtendedAuthRequest_PR_NOTHING,	/* No components present */
	InnerExtendedAuthRequest_PR_and,
	InnerExtendedAuthRequest_PR_or,
	InnerExtendedAuthRequest_PR_contents
} InnerExtendedAuthRequest_PR;

/* Forward declarations */
struct InnerExtendedAuthRequest;

/* InnerExtendedAuthRequest */
typedef struct InnerExtendedAuthRequest {
	InnerExtendedAuthRequest_PR present;
	union InnerExtendedAuthRequest_u {
		struct InnerExtendedAuthRequest__and {
			A_SEQUENCE_OF(struct InnerExtendedAuthRequest) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} And;
		struct InnerExtendedAuthRequest__or {
			A_SEQUENCE_OF(struct InnerExtendedAuthRequest) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} Or;
		AtomicExtendedAuthRequest_t	 contents;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InnerExtendedAuthRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InnerExtendedAuthRequest;
extern asn_CHOICE_specifics_t asn_SPC_InnerExtendedAuthRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_InnerExtendedAuthRequest_1[3];
extern asn_per_constraints_t asn_PER_type_InnerExtendedAuthRequest_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "InnerExtendedAuthRequest.h"

#endif	/* _InnerExtendedAuthRequest_H_ */
#include <asn_internal.h>
