/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "../../asn1/../ttcn/AtsIS/lib/asn1/iso-patched/EfcDsrcApplication.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_Int1_H_
#define	_Int1_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Int1 */
typedef long	 Int1_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Int1_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Int1;
asn_struct_free_f Int1_free;
asn_struct_print_f Int1_print;
asn_constr_check_f Int1_constraint;
ber_type_decoder_f Int1_decode_ber;
der_type_encoder_f Int1_encode_der;
xer_type_decoder_f Int1_decode_xer;
xer_type_encoder_f Int1_encode_xer;
jer_type_encoder_f Int1_encode_jer;
oer_type_decoder_f Int1_decode_oer;
oer_type_encoder_f Int1_encode_oer;
per_type_decoder_f Int1_decode_uper;
per_type_encoder_f Int1_encode_uper;
per_type_decoder_f Int1_decode_aper;
per_type_encoder_f Int1_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Int1_H_ */
#include <asn_internal.h>
