/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Iso21177AccessControl"
 * 	found in "../../asn1/../ttcn/Ats21177/21177/EN_ISO_21177_access_control.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "Iso21177AccessCtrlPduId.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "AccessControlResult.h"
#include "ExtendedAuthPdu.h"
#include "EnhancedAuthPdu.h"
#include "SecurityMgmtInfoPdu.h"
#include "SessionExtensionPdu.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>
#ifndef	_Iso21177AccessControlPdu_H_
#define	_Iso21177AccessControlPdu_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Iso21177AccessControlPdu__value_PR {
	Iso21177AccessControlPdu__value_PR_NOTHING,	/* No components present */
	Iso21177AccessControlPdu__value_PR_AccessControlResult,
	Iso21177AccessControlPdu__value_PR_ExtendedAuthPdu,
	Iso21177AccessControlPdu__value_PR_EnhancedAuthPdu,
	Iso21177AccessControlPdu__value_PR_SecurityMgmtInfoPdu,
	Iso21177AccessControlPdu__value_PR_SessionExtensionPdu
} Iso21177AccessControlPdu__value_PR;

/* Iso21177AccessControlPdu */
typedef struct Iso21177AccessControlPdu {
	Iso21177AccessCtrlPduId_t	 messageId;
	struct Iso21177AccessControlPdu__value {
		Iso21177AccessControlPdu__value_PR present;
		union Iso21177AccessControlPdu__value_u {
			AccessControlResult_t	 AccessControlResult;
			ExtendedAuthPdu_t	 ExtendedAuthPdu;
			EnhancedAuthPdu_t	 EnhancedAuthPdu;
			SecurityMgmtInfoPdu_t	 SecurityMgmtInfoPdu;
			SessionExtensionPdu_t	 SessionExtensionPdu;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Iso21177AccessControlPdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Iso21177AccessControlPdu;
extern asn_SEQUENCE_specifics_t asn_SPC_Iso21177AccessControlPdu_specs_1;
extern asn_TYPE_member_t asn_MBR_Iso21177AccessControlPdu_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Iso21177AccessControlPdu_H_ */
#include <asn_internal.h>
