/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Iso21177AdaptorLayer"
 * 	found in "../../asn1/../ttcn/Ats21177/21177/EN_ISO_21177_adaptor_layer.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "Iso21177AdaptorLayerPduId.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "Apdu.h"
#include "AccessControl.h"
#include "TlsClientMsg1.h"
#include "TlsServerMsg1.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>
#ifndef	_Iso21177AdaptorLayerPdu_H_
#define	_Iso21177AdaptorLayerPdu_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Iso21177AdaptorLayerPdu__value_PR {
	Iso21177AdaptorLayerPdu__value_PR_NOTHING,	/* No components present */
	Iso21177AdaptorLayerPdu__value_PR_Apdu,
	Iso21177AdaptorLayerPdu__value_PR_AccessControl,
	Iso21177AdaptorLayerPdu__value_PR_TlsClientMsg1,
	Iso21177AdaptorLayerPdu__value_PR_TlsServerMsg1
} Iso21177AdaptorLayerPdu__value_PR;

/* Iso21177AdaptorLayerPdu */
typedef struct Iso21177AdaptorLayerPdu {
	Iso21177AdaptorLayerPduId_t	 messageId;
	struct Iso21177AdaptorLayerPdu__value {
		Iso21177AdaptorLayerPdu__value_PR present;
		union Iso21177AdaptorLayerPdu__value_u {
			Apdu_t	 Apdu;
			AccessControl_t	 AccessControl;
			TlsClientMsg1_t	 TlsClientMsg1;
			TlsServerMsg1_t	 TlsServerMsg1;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Iso21177AdaptorLayerPdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Iso21177AdaptorLayerPdu;

#ifdef __cplusplus
}
#endif

#endif	/* _Iso21177AdaptorLayerPdu_H_ */
#include <asn_internal.h>
