/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC-noCircular"
 * 	found in "../../asn1/../ttcn/AtsIS/lib/asn1/iso-patched/DSRC_noCircular.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#ifndef	_LaneDataAttributeList_H_
#define	_LaneDataAttributeList_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LaneDataAttribute;

/* LaneDataAttributeList */
typedef struct LaneDataAttributeList {
	A_SEQUENCE_OF(struct LaneDataAttribute) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LaneDataAttributeList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LaneDataAttributeList;
extern asn_SET_OF_specifics_t asn_SPC_LaneDataAttributeList_specs_1;
extern asn_TYPE_member_t asn_MBR_LaneDataAttributeList_1[1];
extern asn_per_constraints_t asn_PER_type_LaneDataAttributeList_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "LaneDataAttribute.h"

#endif	/* _LaneDataAttributeList_H_ */
#include <asn_internal.h>
