/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "../../asn1/../ttcn/../build/asn1/ISO_TS_19321/IVI.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "GoodsType.h"
#include "DangerousGoodsBasic.h"
#include "SpecialTransportType.h"
#include <constr_SEQUENCE.h>
#ifndef	_LoadType_H_
#define	_LoadType_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LoadType */
typedef struct LoadType {
	GoodsType_t	 goodsType;
	DangerousGoodsBasic_t	 dangerousGoodsType;
	SpecialTransportType_t	 specialTransportType;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LoadType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LoadType;
extern asn_SEQUENCE_specifics_t asn_SPC_LoadType_specs_1;
extern asn_TYPE_member_t asn_MBR_LoadType_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _LoadType_H_ */
#include <asn_internal.h>
