/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "../../asn1/../ttcn/../build/asn1/ISO_TS_19321/IVI.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_MaxNoOfVehicles_H_
#define	_MaxNoOfVehicles_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MaxNoOfVehicles */
typedef long	 MaxNoOfVehicles_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_MaxNoOfVehicles_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_MaxNoOfVehicles;
asn_struct_free_f MaxNoOfVehicles_free;
asn_struct_print_f MaxNoOfVehicles_print;
asn_constr_check_f MaxNoOfVehicles_constraint;
ber_type_decoder_f MaxNoOfVehicles_decode_ber;
der_type_encoder_f MaxNoOfVehicles_encode_der;
xer_type_decoder_f MaxNoOfVehicles_decode_xer;
xer_type_encoder_f MaxNoOfVehicles_encode_xer;
jer_type_encoder_f MaxNoOfVehicles_encode_jer;
oer_type_decoder_f MaxNoOfVehicles_decode_oer;
oer_type_encoder_f MaxNoOfVehicles_encode_oer;
per_type_decoder_f MaxNoOfVehicles_decode_uper;
per_type_encoder_f MaxNoOfVehicles_encode_uper;
per_type_decoder_f MaxNoOfVehicles_decode_aper;
per_type_encoder_f MaxNoOfVehicles_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _MaxNoOfVehicles_H_ */
#include <asn_internal.h>
