/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2"
 * 	found in "../../asn1/../ttcn/AtsSecurity/lib/asn1/ieee1609dot2/Ieee1609Dot2.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "HashedId3.h"
#include "CrlSeries.h"
#include <constr_SEQUENCE.h>
#ifndef	_MissingCrlIdentifier_H_
#define	_MissingCrlIdentifier_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MissingCrlIdentifier */
typedef struct MissingCrlIdentifier {
	HashedId3_t	 cracaId;
	CrlSeries_t	 crlSeries;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MissingCrlIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MissingCrlIdentifier;
extern asn_SEQUENCE_specifics_t asn_SPC_MissingCrlIdentifier_specs_1;
extern asn_TYPE_member_t asn_MBR_MissingCrlIdentifier_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _MissingCrlIdentifier_H_ */
#include <asn_internal.h>
