/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC-noCircular"
 * 	found in "../../asn1/../ttcn/AtsIS/lib/asn1/iso-patched/DSRC_noCircular.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "Offset-B16.h"
#include <constr_SEQUENCE.h>
#ifndef	_Node_XY_32b_H_
#define	_Node_XY_32b_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Node-XY-32b */
typedef struct Node_XY_32b {
	Offset_B16_t	 x;
	Offset_B16_t	 y;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Node_XY_32b_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Node_XY_32b;
extern asn_SEQUENCE_specifics_t asn_SPC_Node_XY_32b_specs_1;
extern asn_TYPE_member_t asn_MBR_Node_XY_32b_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Node_XY_32b_H_ */
#include <asn_internal.h>
