/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs102941BaseTypes"
 * 	found in "../../asn1/../ttcn/AtsPki/lib/asn1/EtsiTs102941BaseTypes.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "PublicVerificationKey.h"
#include <constr_SEQUENCE.h>
#ifndef	_PublicKeys_H_
#define	_PublicKeys_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PublicEncryptionKey;

/* PublicKeys */
typedef struct PublicKeys {
	PublicVerificationKey_t	 verificationKey;
	struct PublicEncryptionKey	*encryptionKey;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PublicKeys_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PublicKeys;
extern asn_SEQUENCE_specifics_t asn_SPC_PublicKeys_specs_1;
extern asn_TYPE_member_t asn_MBR_PublicKeys_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PublicEncryptionKey.h"

#endif	/* _PublicKeys_H_ */
#include <asn_internal.h>
