/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1EeRaInterface"
 * 	found in "../../asn1/../ttcn/AtsPki/lib/asn1/ieee_1609.2.1/Ieee1609Dot2Dot1EeRaInterface.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "Uint8.h"
#include "Time32.h"
#include "HashedId8.h"
#include "IValue.h"
#include <constr_SEQUENCE.h>
#ifndef	_RaEeCertAck_H_
#define	_RaEeCertAck_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RaEeCertAck */
typedef struct RaEeCertAck {
	Uint8_t	 version;
	Time32_t	 generationTime;
	HashedId8_t	 requestHash;
	IValue_t	*firstI;	/* OPTIONAL */
	Time32_t	 nextDlTime;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RaEeCertAck_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RaEeCertAck;
extern asn_SEQUENCE_specifics_t asn_SPC_RaEeCertAck_specs_1;
extern asn_TYPE_member_t asn_MBR_RaEeCertAck_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _RaEeCertAck_H_ */
#include <asn_internal.h>
