/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "../../asn1/../ttcn/AtsIS/lib/asn1/iso-patched/EfcDsrcApplication.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "ICC-Id.h"
#ifndef	_ReceiptICC_Id_H_
#define	_ReceiptICC_Id_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReceiptICC-Id */
typedef ICC_Id_t	 ReceiptICC_Id_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReceiptICC_Id;
asn_struct_free_f ReceiptICC_Id_free;
asn_struct_print_f ReceiptICC_Id_print;
asn_constr_check_f ReceiptICC_Id_constraint;
ber_type_decoder_f ReceiptICC_Id_decode_ber;
der_type_encoder_f ReceiptICC_Id_encode_der;
xer_type_decoder_f ReceiptICC_Id_decode_xer;
xer_type_encoder_f ReceiptICC_Id_encode_xer;
jer_type_encoder_f ReceiptICC_Id_encode_jer;
oer_type_decoder_f ReceiptICC_Id_decode_oer;
oer_type_encoder_f ReceiptICC_Id_encode_oer;
per_type_decoder_f ReceiptICC_Id_decode_uper;
per_type_encoder_f ReceiptICC_Id_encode_uper;
per_type_decoder_f ReceiptICC_Id_decode_aper;
per_type_encoder_f ReceiptICC_Id_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ReceiptICC_Id_H_ */
#include <asn_internal.h>
