/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "../../asn1/../ttcn/AtsIS/lib/asn1/iso-patched/EfcDsrcApplication.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "PersonalAccountNumber.h"
#include "PaymentFee.h"
#include "PurseBalance.h"
#include "Int4.h"
#include <constr_SEQUENCE.h>
#ifndef	_ReceiptFinancialPart_H_
#define	_ReceiptFinancialPart_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReceiptFinancialPart */
typedef struct ReceiptFinancialPart {
	PersonalAccountNumber_t	 personalAccountNumber;
	PaymentFee_t	 sessionPaymentFee;
	PurseBalance_t	 sessionCurrentBalance;
	Int4_t	 receiptFinancialSerialNumber;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReceiptFinancialPart_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReceiptFinancialPart;

#ifdef __cplusplus
}
#endif

#endif	/* _ReceiptFinancialPart_H_ */
#include <asn_internal.h>
