/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "../../asn1/../ttcn/AtsIS/lib/asn1/iso-patched/EfcDsrcApplication.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include <OCTET_STRING.h>
#ifndef	_ResultFin_H_
#define	_ResultFin_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ResultFin */
typedef OCTET_STRING_t	 ResultFin_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ResultFin_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ResultFin;
asn_struct_free_f ResultFin_free;
asn_struct_print_f ResultFin_print;
asn_constr_check_f ResultFin_constraint;
ber_type_decoder_f ResultFin_decode_ber;
der_type_encoder_f ResultFin_encode_der;
xer_type_decoder_f ResultFin_decode_xer;
xer_type_encoder_f ResultFin_encode_xer;
jer_type_encoder_f ResultFin_encode_jer;
oer_type_decoder_f ResultFin_decode_oer;
oer_type_encoder_f ResultFin_encode_oer;
per_type_decoder_f ResultFin_decode_uper;
per_type_encoder_f ResultFin_encode_uper;
per_type_decoder_f ResultFin_decode_aper;
per_type_encoder_f ResultFin_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ResultFin_H_ */
#include <asn_internal.h>
