/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "../../asn1/../ttcn/../build/asn1/ISO_TS_19321/IVI.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "Condition.h"
#include "IVI_Temperature.h"
#include "Depth.h"
#include "TreatmentType.h"
#include <constr_SEQUENCE.h>
#ifndef	_RoadSurfaceDynamicCharacteristics_H_
#define	_RoadSurfaceDynamicCharacteristics_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RoadSurfaceDynamicCharacteristics */
typedef struct RoadSurfaceDynamicCharacteristics {
	Condition_t	 condition;
	IVI_Temperature_t	 temperature;
	Depth_t	 iceOrWaterDepth;
	TreatmentType_t	 treatment;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RoadSurfaceDynamicCharacteristics_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RoadSurfaceDynamicCharacteristics;
extern asn_SEQUENCE_specifics_t asn_SPC_RoadSurfaceDynamicCharacteristics_specs_1;
extern asn_TYPE_member_t asn_MBR_RoadSurfaceDynamicCharacteristics_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _RoadSurfaceDynamicCharacteristics_H_ */
#include <asn_internal.h>
