/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Iso21177AccessControl"
 * 	found in "../../asn1/../ttcn/Ats21177/21177/EN_ISO_21177_access_control.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include <OCTET_STRING.h>
#include "SecurityMgmtInfoRequestId.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "EtsiTs102941CrlRequest.h"
#include "EtsiTs102941CtlRequest.h"
#include "IeeeCrlRequest.h"
#include "CertChainRequest.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>
#ifndef	_SecurityMgmtInfoRequest_H_
#define	_SecurityMgmtInfoRequest_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SecurityMgmtInfoRequest__value_PR {
	SecurityMgmtInfoRequest__value_PR_NOTHING,	/* No components present */
	SecurityMgmtInfoRequest__value_PR_EtsiTs102941CrlRequest,
	SecurityMgmtInfoRequest__value_PR_EtsiTs102941CtlRequest,
	SecurityMgmtInfoRequest__value_PR_IeeeCrlRequest,
	SecurityMgmtInfoRequest__value_PR_CertChainRequest
} SecurityMgmtInfoRequest__value_PR;

/* SecurityMgmtInfoRequest */
typedef struct SecurityMgmtInfoRequest {
	OCTET_STRING_t	 id;
	SecurityMgmtInfoRequestId_t	 messageId;
	struct SecurityMgmtInfoRequest__value {
		SecurityMgmtInfoRequest__value_PR present;
		union SecurityMgmtInfoRequest__value_u {
			EtsiTs102941CrlRequest_t	 EtsiTs102941CrlRequest;
			EtsiTs102941CtlRequest_t	 EtsiTs102941CtlRequest;
			IeeeCrlRequest_t	 IeeeCrlRequest;
			CertChainRequest_t	 CertChainRequest;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SecurityMgmtInfoRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SecurityMgmtInfoRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_SecurityMgmtInfoRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_SecurityMgmtInfoRequest_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SecurityMgmtInfoRequest_H_ */
#include <asn_internal.h>
