/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Iso21177AccessControl"
 * 	found in "../../asn1/../ttcn/Ats21177/21177/EN_ISO_21177_access_control.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include <NativeEnumerated.h>
#ifndef	_SecurityMgmtInfoErrorResponse_H_
#define	_SecurityMgmtInfoErrorResponse_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SecurityMgmtInfoErrorResponse {
	SecurityMgmtInfoErrorResponse_unavailable	= 0,
	SecurityMgmtInfoErrorResponse_inappropriate_type	= 1
	/*
	 * Enumeration is extensible
	 */
} e_SecurityMgmtInfoErrorResponse;

/* SecurityMgmtInfoErrorResponse */
typedef long	 SecurityMgmtInfoErrorResponse_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SecurityMgmtInfoErrorResponse_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SecurityMgmtInfoErrorResponse;
extern const asn_INTEGER_specifics_t asn_SPC_SecurityMgmtInfoErrorResponse_specs_1;
asn_struct_free_f SecurityMgmtInfoErrorResponse_free;
asn_struct_print_f SecurityMgmtInfoErrorResponse_print;
asn_constr_check_f SecurityMgmtInfoErrorResponse_constraint;
ber_type_decoder_f SecurityMgmtInfoErrorResponse_decode_ber;
der_type_encoder_f SecurityMgmtInfoErrorResponse_encode_der;
xer_type_decoder_f SecurityMgmtInfoErrorResponse_decode_xer;
xer_type_encoder_f SecurityMgmtInfoErrorResponse_encode_xer;
jer_type_encoder_f SecurityMgmtInfoErrorResponse_encode_jer;
oer_type_decoder_f SecurityMgmtInfoErrorResponse_decode_oer;
oer_type_encoder_f SecurityMgmtInfoErrorResponse_encode_oer;
per_type_decoder_f SecurityMgmtInfoErrorResponse_decode_uper;
per_type_encoder_f SecurityMgmtInfoErrorResponse_encode_uper;
per_type_decoder_f SecurityMgmtInfoErrorResponse_decode_aper;
per_type_encoder_f SecurityMgmtInfoErrorResponse_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SecurityMgmtInfoErrorResponse_H_ */
#include <asn_internal.h>
