/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Iso21177AccessControl"
 * 	found in "../../asn1/../ttcn/Ats21177/21177/EN_ISO_21177_access_control.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "SecurityMgmtInfoRequest.h"
#include "SecurityMgmtInfoResponse.h"
#include <constr_CHOICE.h>
#ifndef	_SecurityMgmtInfoPdu_H_
#define	_SecurityMgmtInfoPdu_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SecurityMgmtInfoPdu_PR {
	SecurityMgmtInfoPdu_PR_NOTHING,	/* No components present */
	SecurityMgmtInfoPdu_PR_request,
	SecurityMgmtInfoPdu_PR_response
	/* Extensions may appear below */
	
} SecurityMgmtInfoPdu_PR;

/* SecurityMgmtInfoPdu */
typedef struct SecurityMgmtInfoPdu {
	SecurityMgmtInfoPdu_PR present;
	union SecurityMgmtInfoPdu_u {
		SecurityMgmtInfoRequest_t	 request;
		SecurityMgmtInfoResponse_t	 response;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SecurityMgmtInfoPdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SecurityMgmtInfoPdu;
extern asn_CHOICE_specifics_t asn_SPC_SecurityMgmtInfoPdu_specs_1;
extern asn_TYPE_member_t asn_MBR_SecurityMgmtInfoPdu_1[2];
extern asn_per_constraints_t asn_PER_type_SecurityMgmtInfoPdu_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SecurityMgmtInfoPdu_H_ */
#include <asn_internal.h>
