/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Iso21177AccessControl"
 * 	found in "../../asn1/../ttcn/Ats21177/21177/EN_ISO_21177_access_control.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_SecurityMgmtInfoResponseId_H_
#define	_SecurityMgmtInfoResponseId_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SecurityMgmtInfoResponseId */
typedef long	 SecurityMgmtInfoResponseId_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SecurityMgmtInfoResponseId_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SecurityMgmtInfoResponseId;
asn_struct_free_f SecurityMgmtInfoResponseId_free;
asn_struct_print_f SecurityMgmtInfoResponseId_print;
asn_constr_check_f SecurityMgmtInfoResponseId_constraint;
ber_type_decoder_f SecurityMgmtInfoResponseId_decode_ber;
der_type_encoder_f SecurityMgmtInfoResponseId_encode_der;
xer_type_decoder_f SecurityMgmtInfoResponseId_decode_xer;
xer_type_encoder_f SecurityMgmtInfoResponseId_encode_xer;
jer_type_encoder_f SecurityMgmtInfoResponseId_encode_jer;
oer_type_decoder_f SecurityMgmtInfoResponseId_decode_oer;
oer_type_encoder_f SecurityMgmtInfoResponseId_encode_oer;
per_type_decoder_f SecurityMgmtInfoResponseId_decode_uper;
per_type_encoder_f SecurityMgmtInfoResponseId_encode_uper;
per_type_decoder_f SecurityMgmtInfoResponseId_decode_aper;
per_type_encoder_f SecurityMgmtInfoResponseId_encode_aper;
#define SecurityMgmtInfoResponseId_securityMgmtInfoResponseId_reserved	((SecurityMgmtInfoResponseId_t)0)
#define SecurityMgmtInfoResponseId_securityMgmtInfoErrorId	((SecurityMgmtInfoResponseId_t)1)
#define SecurityMgmtInfoResponseId_etsiCrlResponseId	((SecurityMgmtInfoResponseId_t)2)
#define SecurityMgmtInfoResponseId_etsiCtlResponseId	((SecurityMgmtInfoResponseId_t)3)
#define SecurityMgmtInfoResponseId_ieeeCrlResponseId	((SecurityMgmtInfoResponseId_t)4)
#define SecurityMgmtInfoResponseId_certChainResponseId	((SecurityMgmtInfoResponseId_t)5)

#ifdef __cplusplus
}
#endif

#endif	/* _SecurityMgmtInfoResponseId_H_ */
#include <asn_internal.h>
