/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Iso21177AccessControl"
 * 	found in "../../asn1/../ttcn/Ats21177/21177/EN_ISO_21177_access_control.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "HashedId8.h"
#ifndef	_SessionExtensionAck_H_
#define	_SessionExtensionAck_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SessionExtensionAck */
typedef HashedId8_t	 SessionExtensionAck_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SessionExtensionAck_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SessionExtensionAck;
asn_struct_free_f SessionExtensionAck_free;
asn_struct_print_f SessionExtensionAck_print;
asn_constr_check_f SessionExtensionAck_constraint;
ber_type_decoder_f SessionExtensionAck_decode_ber;
der_type_encoder_f SessionExtensionAck_encode_der;
xer_type_decoder_f SessionExtensionAck_decode_xer;
xer_type_encoder_f SessionExtensionAck_encode_xer;
jer_type_encoder_f SessionExtensionAck_encode_jer;
oer_type_decoder_f SessionExtensionAck_decode_oer;
oer_type_encoder_f SessionExtensionAck_encode_oer;
per_type_decoder_f SessionExtensionAck_decode_uper;
per_type_encoder_f SessionExtensionAck_encode_uper;
per_type_decoder_f SessionExtensionAck_decode_aper;
per_type_encoder_f SessionExtensionAck_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SessionExtensionAck_H_ */
#include <asn_internal.h>
