/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Iso21177AccessControl"
 * 	found in "../../asn1/../ttcn/Ats21177/21177/EN_ISO_21177_access_control.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_SessionExtensionPduId_H_
#define	_SessionExtensionPduId_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SessionExtensionPduId */
typedef long	 SessionExtensionPduId_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SessionExtensionPduId_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SessionExtensionPduId;
asn_struct_free_f SessionExtensionPduId_free;
asn_struct_print_f SessionExtensionPduId_print;
asn_constr_check_f SessionExtensionPduId_constraint;
ber_type_decoder_f SessionExtensionPduId_decode_ber;
der_type_encoder_f SessionExtensionPduId_encode_der;
xer_type_decoder_f SessionExtensionPduId_decode_xer;
xer_type_encoder_f SessionExtensionPduId_encode_xer;
jer_type_encoder_f SessionExtensionPduId_encode_jer;
oer_type_decoder_f SessionExtensionPduId_decode_oer;
oer_type_encoder_f SessionExtensionPduId_encode_oer;
per_type_decoder_f SessionExtensionPduId_decode_uper;
per_type_encoder_f SessionExtensionPduId_encode_uper;
per_type_decoder_f SessionExtensionPduId_decode_aper;
per_type_encoder_f SessionExtensionPduId_encode_aper;
#define SessionExtensionPduId_sessionExtensionPduId_reserved	((SessionExtensionPduId_t)0)
#define SessionExtensionPduId_sessionExtensionOuterId	((SessionExtensionPduId_t)1)
#define SessionExtensionPduId_sessionExtensionInnerId	((SessionExtensionPduId_t)2)
#define SessionExtensionPduId_sessionExtensionContentsId	((SessionExtensionPduId_t)3)
#define SessionExtensionPduId_sessionExtensionAckId	((SessionExtensionPduId_t)4)

#ifdef __cplusplus
}
#endif

#endif	/* _SessionExtensionPduId_H_ */
#include <asn_internal.h>
