/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Iso21177AccessControl"
 * 	found in "../../asn1/../ttcn/Ats21177/21177/EN_ISO_21177_access_control.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "SessionExtensionPduId.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "SessionExtensionOuter.h"
#include "SessionExtensionInner.h"
#include "SessionExtensionContents.h"
#include "SessionExtensionAck.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>
#ifndef	_SessionExtensionPdu_H_
#define	_SessionExtensionPdu_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SessionExtensionPdu__value_PR {
	SessionExtensionPdu__value_PR_NOTHING,	/* No components present */
	SessionExtensionPdu__value_PR_SessionExtensionOuter,
	SessionExtensionPdu__value_PR_SessionExtensionInner,
	SessionExtensionPdu__value_PR_SessionExtensionContents,
	SessionExtensionPdu__value_PR_SessionExtensionAck
} SessionExtensionPdu__value_PR;

/* SessionExtensionPdu */
typedef struct SessionExtensionPdu {
	SessionExtensionPduId_t	 messageId;
	struct SessionExtensionPdu__value {
		SessionExtensionPdu__value_PR present;
		union SessionExtensionPdu__value_u {
			SessionExtensionOuter_t	 SessionExtensionOuter;
			SessionExtensionInner_t	 SessionExtensionInner;
			SessionExtensionContents_t	 SessionExtensionContents;
			SessionExtensionAck_t	 SessionExtensionAck;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SessionExtensionPdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SessionExtensionPdu;
extern asn_SEQUENCE_specifics_t asn_SPC_SessionExtensionPdu_specs_1;
extern asn_TYPE_member_t asn_MBR_SessionExtensionPdu_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _SessionExtensionPdu_H_ */
#include <asn_internal.h>
