/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2Dot1Protocol"
 * 	found in "../../asn1/../ttcn/AtsPki/lib/asn1/ieee_1609.2.1/Ieee1609Dot2Dot1Protocol.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "HashAlgorithm.h"
#include "ScopedCertificateRequest.h"
#include "SignerIdentifier.h"
#include "Signature.h"
#include <constr_SEQUENCE.h>
#ifndef	_SignedCertificateRequest_H_
#define	_SignedCertificateRequest_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SignedCertificateRequest */
typedef struct SignedCertificateRequest {
	HashAlgorithm_t	 hashAlgorithmId;
	ScopedCertificateRequest_t	 tbsRequest;
	SignerIdentifier_t	 signer;
	Signature_t	 signature;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignedCertificateRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignedCertificateRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _SignedCertificateRequest_H_ */
#include <asn_internal.h>
