/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "Iso21177AdaptorLayer"
 * 	found in "../../asn1/../ttcn/Ats21177/21177/EN_ISO_21177_adaptor_layer.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>
#ifndef	_TlsServerMsg1_H_
#define	_TlsServerMsg1_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TlsServerMsg1 */
typedef struct TlsServerMsg1 {
	OCTET_STRING_t	 serverHelloMsg;
	OCTET_STRING_t	 brokerInfo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TlsServerMsg1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TlsServerMsg1;
extern asn_SEQUENCE_specifics_t asn_SPC_TlsServerMsg1_specs_1;
extern asn_TYPE_member_t asn_MBR_TlsServerMsg1_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _TlsServerMsg1_H_ */
#include <asn_internal.h>
