/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "../../asn1/../ttcn/AtsIS/lib/asn1/iso-patched/EfcDsrcApplication.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "Int2.h"
#ifndef	_VehicleWeightLaden_H_
#define	_VehicleWeightLaden_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleWeightLaden */
typedef Int2_t	 VehicleWeightLaden_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleWeightLaden;
asn_struct_free_f VehicleWeightLaden_free;
asn_struct_print_f VehicleWeightLaden_print;
asn_constr_check_f VehicleWeightLaden_constraint;
ber_type_decoder_f VehicleWeightLaden_decode_ber;
der_type_encoder_f VehicleWeightLaden_encode_der;
xer_type_decoder_f VehicleWeightLaden_decode_xer;
xer_type_encoder_f VehicleWeightLaden_encode_xer;
jer_type_encoder_f VehicleWeightLaden_encode_jer;
oer_type_decoder_f VehicleWeightLaden_decode_oer;
oer_type_encoder_f VehicleWeightLaden_encode_oer;
per_type_decoder_f VehicleWeightLaden_decode_uper;
per_type_encoder_f VehicleWeightLaden_encode_uper;
per_type_decoder_f VehicleWeightLaden_decode_aper;
per_type_encoder_f VehicleWeightLaden_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleWeightLaden_H_ */
#include <asn_internal.h>
