/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "../../asn1/../ttcn/../build/asn1/ISO_TS_19321/IVI.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include <NativeInteger.h>
#ifndef	_Zid_H_
#define	_Zid_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Zid */
typedef long	 Zid_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Zid_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Zid;
asn_struct_free_f Zid_free;
asn_struct_print_f Zid_print;
asn_constr_check_f Zid_constraint;
ber_type_decoder_f Zid_decode_ber;
der_type_encoder_f Zid_encode_der;
xer_type_decoder_f Zid_decode_xer;
xer_type_encoder_f Zid_encode_xer;
jer_type_encoder_f Zid_encode_jer;
oer_type_decoder_f Zid_decode_oer;
oer_type_encoder_f Zid_encode_oer;
per_type_decoder_f Zid_decode_uper;
per_type_encoder_f Zid_encode_uper;
per_type_decoder_f Zid_decode_aper;
per_type_encoder_f Zid_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Zid_H_ */
#include <asn_internal.h>
