/*
 * Generated by asn1c-0.9.29-DF (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "../../asn1/../ttcn/../build/asn1/ISO_TS_19321/IVI.asn"
 * 	`asn1c -no-gen-example -pdu=Iso21177AccessControlPdu -pdu=ExtendedAuthPdu -pdu=EnhancedAuthPdu -pdu=SecurityMgmtInfoPdu -pdu=SessionExtensionPdu -pdu=Iso21177AdaptorLayerPdu -pdu=EtsiTs103097Data -pdu=EtsiTs103097Certificate -fcompound-names`
 */


/* Including external dependencies */
#include "Zid.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#ifndef	_ZoneIds_H_
#define	_ZoneIds_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ZoneIds */
typedef struct ZoneIds {
	A_SEQUENCE_OF(Zid_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ZoneIds_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ZoneIds;
extern asn_SET_OF_specifics_t asn_SPC_ZoneIds_specs_1;
extern asn_TYPE_member_t asn_MBR_ZoneIds_1[1];
extern asn_per_constraints_t asn_PER_type_ZoneIds_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ZoneIds_H_ */
#include <asn_internal.h>
